os: osx
language: objective-c
osx_image: xcode11.6
before_install: true
install: true
branches:
  only:
    - master
    - main
script:
  - script/build
xcode_workspace: ReactiveObjC.xcworkspace
stages:
  - compile_mac
  - compile_ios
  - compile_tvos
  - compile_watchos
  - compile_pod
  - test_mac
  - test_ios
  - test_tvos
  - test_watchos
jobs:
  include:
    - stage: compile_mac
      script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform mac
      env:
        - JOB=CARTHAGE-macOS
    - stage: compile_ios
      script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform iOS
      env:
        - JOB=CARTHAGE-iOS
    - stage: compile_tvos
      script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform tvOS
      env:
        - JOB=CARTHAGE-tvOS
    - stage: compile_watchos
      script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform watchOS
      env:
        - JOB=CARTHAGE-watchOS
    - stage: compile_pod
      script:
      - gem install cocoapods --pre
      - pod repo update --silent
      - pod lib lint ReactiveObjC.podspec
      env:
        - JOB=PODSPEC
    - stage: test_mac
      xcode_scheme: ReactiveObjC-macOSTests
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION="test"
        - XCODE_DESTINATION="arch=x86_64"
    - stage: test_ios
      xcode_scheme: ReactiveObjC-iOSTests
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="test"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 11"
    - stage: test_tvos
      xcode_scheme: ReactiveObjC-tvOSTests
      env:
        - XCODE_SDK=appletvsimulator
        - XCODE_ACTION="test"
        - XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV 4K"
      xcode_scheme: ReactiveObjC
    - stage: test_watchos
      env:
        - XCODE_SDK=watchsimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=watchOS Simulator,name=Apple Watch - 38mm"
notifications:
  email: false
  slack:
    secure: C9QTry5wUG9CfeH3rm3Z19R5rDWqDO7EhHAqHDXBxT6CpGRkTPFliJexpjBYB4sroJ8CiY5ZgTI2sjRBiAdGoE5ZQkfnwSoKQhWXkwo19TnbSnufr3cKO2SZkUhBqOlZcA+mgfjZ7rm2wm7RhpCR/4z8oBXDN4/xv0U5R2fLCLE=
